#!/bin/sh
# shellcheck shell=dash disable=SC2169,SC3010,SC3015 source=/dev/null
#
# Starts HMServer.
#

CFG_TEMPLATE_DIR=/etc/config_templates
STARTWAITFILE=/var/status/HMServerStarted

[[ -r /var/hm_mode ]] && . /var/hm_mode

# skip this startup if not in normal mode
[[ "${HM_MODE}" != "NORMAL" ]] && exit 0

HM_SERVER=/opt/HMServer/HMIPServer.jar:/opt/HMServer/coupling/ESHBridge.jar
HM_SERVER_CLASS="de.eq3.ccu.server.ip.HMIPServer"
HM_SERVER_ARGS="/var/etc/crRFD.conf /var/etc/HMServer.conf"
HM_SERVER_DEVNODE=/dev/mmd_hmip
LOGLEVEL_HMIP=error
PIDFILE=/var/run/HMIPServer.pid
NTPSYNC_TIMEOUT=180

init() {
  export JAVA_HOME=/opt/java/
  export PATH=${PATH}:${JAVA_HOME}/bin

  if [[ ! -e /etc/config/hmip_networkkey.conf ]]; then
    if [[ -f ${CFG_TEMPLATE_DIR}/hmip_networkkey.conf ]]; then
      cp -a ${CFG_TEMPLATE_DIR}/hmip_networkkey.conf /etc/config
    fi
  fi

  # create a log4j2.xml config file in /var/etc and modify it
  # according to the syslog settings in /etc/config/syslog
  cp -a ${CFG_TEMPLATE_DIR}/log4j2.xml /var/etc/

  # get the current syslog settings
  [[ -r /etc/config/syslog ]] && . /etc/config/syslog

  # check if we have an external loghost and if so, modify
  # the SYSLOG appender in log4j2.xml accordingly.
  if [[ -n "${LOGHOST}" ]]; then
    sed -i "s|host=\"127\.0\.0\.1\"|host=\"${LOGHOST}\"|" /var/etc/log4j2.xml
    sed -i "/AppenderRef ref=\"File\"/a\\    <AppenderRef ref=\"SYSLOG\"\\/>" /var/etc/log4j2.xml
  fi

  # modify "priority value" values in log4j2.xml to set the
  # global loglevel
  sed -i "s/level=\".*\"/level=\"$(echo ${LOGLEVEL_HMIP} | tr '[:upper:]' '[:lower:]')\"/g" /var/etc/log4j2.xml

  # if the userfs is located on a non-mmc device (not on a SD card)
  # we can safely use the old /usr/local/sdcard directory path as
  # the general storagePath for diagrams and daily backups
  storagePath=""
  if [[ "${HM_HOST}" =~ oci\|lxc ]] ||
     grep " /usr/local " /proc/mounts | grep -qv "^/dev/mmc"; then
    storagePath="/usr/local/sdcard"
    mkdir -p ${storagePath}
  fi

  # users can override the storagePath by specifying an own storage
  # path in /etc/config/CustomStoragePath
  if [[ -f /etc/config/CustomStoragePath ]]; then
    storagePath=$(cat /etc/config/CustomStoragePath)
  fi

  # in case a storagePath is specified we make sure it is setup
  # correct and in case it is empty or does not exist we skip this
  # so that the WebUI will remind users to insert an USB drive for
  # storing diagrams+backups
  if [[ -n "${storagePath}" ]] && [[ -d "${storagePath}" ]]; then
    if [[ ! -d "${storagePath}/measurement" ]]; then
      mkdir -p "${storagePath}/measurement"
    fi
    if [[ ! -e "${storagePath}/.nobackup" ]]; then
      touch "${storagePath}/.nobackup"
    fi
    ln -sfn "${storagePath}" /media/usb0
    touch /var/status/SDinitialised
    touch /var/status/hasSD
  fi

  # lets build HMServer.conf with own diagram path
  sed "s|^diagramDatabasePath=.*$|diagramDatabasePath=/tmp/measurement|" /etc/HMServer.conf >/var/etc/HMServer.conf

  # copy over the diagram measurement data from /media/usb0/measurement to
  # /tmp/measurement so that we have the rrd data to start with
  if [[ -d /media/usb0/measurement ]]; then
    rm -rf /tmp/measurement
    cp -a /media/usb0/measurement /tmp/
  else
    mkdir -p /tmp/measurement
  fi

  # sanitize the /etc/config/firmware path to make sure no directory without
  # an 'info' file or info file without any "Name=" entry is located within
  # (cf. https://github.com/openccu/openccu/issues/1302)
  for dir in /etc/config/firmware/*; do
    if [[ -d "${dir}" ]]; then
      if [[ ! -f "${dir}/info" ]] || ! grep -q -e "Name=." "${dir}/info"; then
        echo -n "WARNING: removed invalid ${dir}, "
        rm -rf "${dir}"
      fi
    fi
  done

  if [[ -n "${HM_HMIP_DEV}" ]]; then

    # if no raw uart is used to connect to the rf module (e.g. HmIP-RFUSB)
    # we have to set the device node
    if [[ "${HM_HMIP_DEVNODE}" != "${HM_HMRF_DEVNODE}" ]] ||
       ! echo -n "${HM_HMIP_DEVNODE}" | grep -q raw-uart; then
      HM_SERVER_DEVNODE=${HM_HMIP_DEVNODE}
    else
      HM_SERVER_DEVNODE=/dev/mmd_hmip
    fi

    # make sure the Adapter Port setting is correct
    # when generating /var/etc/crRFD.conf
    sed "s|^Adapter\.1\.Port=/dev/.*$|Adapter.1.Port=${HM_SERVER_DEVNODE}|" ${CFG_TEMPLATE_DIR}/crRFD.conf >/var/etc/crRFD.conf

    # enable Advanced HmIP capabilities in crRFD.conf if the used HmIP RF module supports it
    if [[ "${HM_HMIP_DEV}" == "RPI-RF-MOD" ]] || [[ "${HM_HMIP_DEV}" == "HMIP-RFUSB" ]]; then
      ADVANCED_HMIP="true"
    else
      ADVANCED_HMIP="false"
    fi

    # set Adapter.Local.Device.Enabled. This will bring up the additional CO-PROCESSOR
    # device which will allow to show up the DutyCycle and CarrierSense parameters.
    sed -i "s|^Adapter\.Local\.Device\.Enabled=.*$|Adapter.Local.Device.Enabled=${ADVANCED_HMIP}|" /var/etc/crRFD.conf

    # set Lan.Routing.Enabled which will enable the advanced HmIP Routing capabilities
    # in crRFD.
    sed -i "s|^Lan\.Routing\.Enabled=.*$|Lan.Routing.Enabled=${ADVANCED_HMIP}|" /var/etc/crRFD.conf

  else
    HM_SERVER=/opt/HMServer/HMServer.jar:/opt/HMServer/coupling/ESHBridge.jar
    HM_SERVER_CLASS="de.eq3.ccu.server.HMServer"
    HM_SERVER_ARGS="/var/etc/HMServer.conf"
    HM_SERVER_DEVNODE=""
  fi
}

waitStartupComplete() {
  STEPS=150
  for i in $(seq 1 ${STEPS}); do
    sleep 2
    echo -n "."
    if [[ -e ${STARTWAITFILE} ]]; then
      echo "OK"
      break
    fi
    if [[ ${i} -eq ${STEPS} ]]; then
      echo "ERROR"
    fi
  done
}

# The HmIP security counter handling of HMIPServer depends on a valid
# system time. If HMIPServer is started with a system time in the past (e.g.
# no RTC and NTP not reachable yet after a power outage) the security counter
# can be set to a wrong value so that all HmIP devices become unreachable
# (cf. https://github.com/OpenCCU/OpenCCU/issues/4274). Thus, if the system
# time could not be taken from a valid RTC (cf. S02InitRTC) we wait (with
# timeout) for a NTP time sync during system startup.
waitTimeSync() {
  if [[ -n "${HM_HMIP_DEV}" ]] &&
     [[ -e /var/status/systemTimeRestored ]] &&
     [[ ! -e /var/status/startupFinished ]] &&
     [[ ! -e /etc/config/NoNTPSyncWait ]] &&
     [[ -x /etc/init.d/S46chronyd ]]; then
    echo -n "NTP sync"
    if /etc/init.d/S46chronyd waitsync ${NTPSYNC_TIMEOUT}; then
      echo -n "OK, "
    else
      echo -n "WARNING: timeout, "
    fi
  fi
}

# Protect the HmIP security counter against the 32 bit overflow in
# HMIPServer (cf. https://github.com/OpenCCU/OpenCCU/issues/4274). At startup
# HMIPServer sets the security counter of the RF module to
#   calc = (now - firstConnect) / 300ms + 1 + securityCounterOffset
# (if calc is greater than the current counter), but only sends the lower
# 32 bits of it. Once calc exceeds 2^32 (e.g. because a start with an
# invalid system time raised the offset) the counter jumps backwards and all
# HmIP devices drop the frames of the CCU as replays. Thus, before HMIPServer
# is started we lower the offset in the access point files so that calc
# stays below 2^32:
#  - prevention: calc = offset+1 is not above the current counter of the RF
#    module, thus HMIPServer keeps that counter and recalculates the offset
#    itself ("Store corrected security counter offset").
#  - repair (one-shot via /etc/config/HmIPSecurityCounterRepair): for a
#    system already in the wrapped state, calc is set slightly above the
#    highest counter the devices most likely have seen (offset+1 + margin).
checkSecurityCounter() {
  [[ -n "${HM_HMIP_DEV}" ]] || return 0

  LIMIT=$((4294967296 - 100000))  # 2^32 minus ~8h of time based increase
  MARGIN=10000000                  # frames sent with an invalid system time
  REPAIR=/etc/config/HmIPSecurityCounterRepair
  NOWMS=$(($(date +%s) * 1000))

  for AP in /etc/config/crRFD/data/*.ap; do
    [[ -f "${AP}" ]] || continue

    # parse the kryo serialized access point (cf. HMIPAccessPointSerializer):
    # class name (varint, varint, string), int version, string id, string
    # address, long firstConnect, string nwkExchangeState, long offset
    # shellcheck disable=SC2046
    set -- $(od -An -v -tu1 "${AP}")
    POS=0; IDX=0; VER=0; FC=0; OFFPOS=0; OFFSET=0
    for FIELD in v v s i s s l s l; do
      IDX=$((IDX + 1))
      [[ ${IDX} -eq 9 ]] && OFFPOS=${POS}
      case "${FIELD}" in
        v) N=1 ;;
        i) N=4 ;;
        l) N=8 ;;
        s) # ASCII string (last char | 0x80) or length prefixed (null/0/1 char)
          if [[ $# -gt 0 ]] && [[ $1 -ge 128 ]]; then
            [[ $1 -ge 192 ]] && break
            N=$(($1 - 128)); [[ ${N} -eq 0 ]] && N=1
          else
            N=1
            while [[ ${N} -le $# ]] && eval "[[ \${${N}} -lt 128 ]]"; do N=$((N + 1)); done
          fi
          ;;
      esac
      [[ $# -ge ${N} ]] || break
      VALUE=0
      while [[ ${N} -gt 0 ]]; do
        VALUE=$(((VALUE << 8) | $1)); shift; POS=$((POS + 1)); N=$((N - 1))
      done
      case "${IDX}" in
        4) VER=${VALUE} ;;
        7) FC=${VALUE} ;;
        9) OFFSET=${VALUE} ;;
      esac
    done
    if [[ ${IDX} -ne 9 ]] || [[ ${VER} -lt 3 ]] || [[ ${VER} -gt 99 ]] ||
       [[ ${FC} -le 0 ]] || [[ ${OFFSET} -ge 4294967296 ]]; then
      continue
    fi

    # predict the calculation of HMIPServer (firstConnect is set to at least
    # 2014-07-01 and is only used if it is in the past)
    [[ ${FC} -lt 1404165600000 ]] && FC=1404165600000
    DIFF=1
    [[ ${FC} -lt ${NOWMS} ]] && DIFF=$(((NOWMS - FC) / 300 + 1))
    if [[ $((DIFF + OFFSET)) -lt ${LIMIT} ]]; then
      # remember that this access point was ok with a valid system time
      [[ ${DIFF} -gt 1 ]] && [[ ! -e "${AP}.checked" ]] && touch "${AP}.checked"
      continue
    fi

    if [[ -e ${REPAIR} ]]; then
      TARGET=$((OFFSET + MARGIN))
    elif [[ -e "${AP}.checked" ]]; then
      TARGET=$((OFFSET + 1))
    else
      # already in the wrapped state before this check existed. Devices may
      # have been power cycled since then and work fine, thus don't touch it.
      echo -n "WARNING: HmIP security counter wrapped, "
      logger -t HMIPServer -p user.warn "security counter of ${AP##*/} already wrapped (offset ${OFFSET}), touch ${REPAIR} to repair"
      continue
    fi
    [[ ${TARGET} -gt ${LIMIT} ]] && TARGET=${LIMIT}
    # NEWOFFSET can be negative (system time far in the future or ~40 years
    # after firstConnect). This is intended: HMIPServer itself stores negative
    # offsets (current counter - time difference) and recalculates the offset
    # at the next start, while skipping the change would wrap the counter.
    NEWOFFSET=$((TARGET - DIFF))

    # write the new offset as 8 byte big endian long
    ESC=""; N=56; BYTES=""
    while [[ ${N} -ge 0 ]]; do
      B=$(((NEWOFFSET >> N) & 255))
      ESC="${ESC}\\$(printf '%03o' "${B}")"; BYTES="${BYTES} ${B}"
      N=$((N - 8))
    done
    [[ -e "${AP}.bak" ]] || cp -a "${AP}" "${AP}.bak"
    cp -a "${AP}" "${AP}.new"
    # shellcheck disable=SC2059
    printf "${ESC}" | dd of="${AP}.new" bs=1 seek="${OFFPOS}" count=8 conv=notrunc 2>/dev/null
    if [[ "$(od -An -v -tu1 -j "${OFFPOS}" -N 8 "${AP}.new" | xargs)" == "${BYTES# }" ]] &&
       mv "${AP}.new" "${AP}"; then
      echo -n "security counter offset fixed, "
      logger -t HMIPServer -p user.warn "security counter offset of ${AP##*/} changed from ${OFFSET} to ${NEWOFFSET} (calc ${TARGET})"
    else
      rm -f "${AP}.new"
      echo -n "ERROR: security counter fix failed, "
    fi
  done
  rm -f ${REPAIR}
}

start() {
  echo -n "Starting HMIPServer: "
  waitTimeSync
  init
  checkSecurityCounter

  # get the architecture
  ARCH=$(uname -m)

  # add "tryReflectionSetAccessible" and --add-opens required for
  # Netty/Vert.x reflective access under Java 9+ strong encapsulation
  # (cf. https://github.com/OpenCCU/OpenCCU/pull/3832)
  JAVAOPT="-Dio.netty.tryReflectionSetAccessible=true"
  JAVAOPT="${JAVAOPT} --add-opens java.base/java.lang=ALL-UNNAMED"
  JAVAOPT="${JAVAOPT} --add-opens java.base/java.util=ALL-UNNAMED"
  JAVAOPT="${JAVAOPT} --add-opens java.base/java.nio=ALL-UNNAMED"
  JAVAOPT="${JAVAOPT} --add-opens java.base/sun.nio.ch=ALL-UNNAMED"
  JAVAOPT="${JAVAOPT} --add-opens java.base/jdk.internal.misc=ALL-UNNAMED"
  JAVAOPT="${JAVAOPT} --add-exports java.base/sun.nio.ch=ALL-UNNAMED"
  JAVAOPT="${JAVAOPT} --add-exports java.base/jdk.internal.misc=ALL-UNNAMED"

  # calculate the maximum used heap size (-Xmx) depending on the
  # total amount of RAM we have (use max. 25%) - use multiple of 128MB
  if [[ -e /sys/fs/cgroup/memory.max ]] && [[ "$(cat /sys/fs/cgroup/memory.max)" != "max" ]]; then
    MAXHEAP=$(awk '{print int(($1/1024/1024)*0.25/128)*128}' /sys/fs/cgroup/memory.max)
  else
    MAXHEAP=$(grep MemTotal: /proc/meminfo | awk '{print int($2/1024*0.25/128)*128}')
  fi
  if [[ -n "${MAXHEAP}" ]] && [[ "${MAXHEAP}" -gt 128 ]]; then
    JAVAOPT="-Xmx${MAXHEAP}m ${JAVAOPT}"
  else
    JAVAOPT="-Xmx128m ${JAVAOPT}"
  fi

  # add gnu.io.rxtx.SerialPorts to cmd line if HM_SERVER_DEVNODE not empty
  if [[ -n "${HM_SERVER_DEVNODE}" ]]; then
    JAVAOPT="-Dgnu.io.rxtx.SerialPorts=${HM_SERVER_DEVNODE} ${JAVAOPT}"

    # check that HM_SERVER_DEVNODE exists and if not error out because then
    # HMIPServer will also not work of course
    if [[ ! -c "${HM_SERVER_DEVNODE}" ]]; then
      echo "ERROR: ${HM_SERVER_DEVNODE} missing"
      exit 1
    fi
  fi

  # adjust the oom score (which is inherited by start-stop-daemon)
  # to ensure that others are killed first in case of low memory situations
  echo -900 >/proc/$$/oom_score_adj 2>/dev/null

  # shellcheck disable=SC2086
  start-stop-daemon -d / -b -S -q -m -p "${PIDFILE}" --exec java -- -Dos.arch=${ARCH} ${JAVAOPT} -Dlog4j.configurationFile=file:///var/etc/log4j2.xml -Dfile.encoding=ISO-8859-1 -cp "${HM_SERVER}" ${HM_SERVER_CLASS} ${HM_SERVER_ARGS}
  echo -n "."
  waitStartupComplete
}

stop() {
  echo -n "Stopping HMIPServer: "
  rm -f ${STARTWAITFILE}
  start-stop-daemon -K -q -p ${PIDFILE}
  rm -f ${PIDFILE}

  # copy over the diagram measurement data from /tmp/measurement to a
  # connected usb stick, if present
  if [[ -d /media/usb0/measurement ]]; then
    /usr/bin/rsync -aogX --delete-after --no-whole-file --checksum /tmp/measurement/ /media/usb0/measurement/
  fi

  echo "OK"
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
