#!/bin/sh
# shellcheck shell=dash disable=SC2169 source=/dev/null
#
# Starts ssdpd
#

OPENCCU_BASE_SERVICE_USERS=yes

DAEMON="ssdpd"
PIDFILE="/var/run/${DAEMON}.pid"

start() {
	echo -n "Starting ${DAEMON}: "

	run_user=root
	if [ "$OPENCCU_BASE_SERVICE_USERS" = yes ]; then
		run_user=ssdp:ssdp
	fi

	# adjust the oom score (which is inherited by start-stop-daemon)
  # to ensure that others are killed first in case of low memory situations
	echo -900 >/proc/$$/oom_score_adj 2> /dev/null

	if start-stop-daemon -d / -S -q -b -m -c "$run_user" -p ${PIDFILE} --exec /bin/${DAEMON}; then
		echo "OK"
	else
		echo "FAIL"
	fi
}
stop() {
	echo -n "Stopping ${DAEMON}: "
	if start-stop-daemon -K -q -p ${PIDFILE}; then
		echo "OK"
	else
		echo "FAIL"
	fi
	rm -f ${PIDFILE}
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
