#!/bin/sh
# shellcheck shell=dash disable=SC2169
#
# Starts ssdpd
#

DAEMON="ssdpd"
PIDFILE="/var/run/${DAEMON}.pid"

start() {
	echo -n "Starting ${DAEMON}: "

	run_user=root
	if [ ! -e /etc/recovery-system ]; then
		run_user=ssdp:ssdp
		# The daemon inherits this preference from start-stop-daemon.
		echo -900 >/proc/$$/oom_score_adj 2> /dev/null
	fi

	if start-stop-daemon -d / -S -q -b -m -c "$run_user" -p ${PIDFILE} --exec /bin/${DAEMON}; then
		echo "OK"
	else
		echo "FAIL"
	fi
}
stop() {
	echo -n "Stopping ${DAEMON}: "
	if start-stop-daemon -K -q -p ${PIDFILE}; then
		echo "OK"
	else
		echo "FAIL"
	fi
	rm -f ${PIDFILE}
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
