---
name: RaspberryMatic CCU (Proxy)
version: 0.4.3
slug: raspberrymatic_proxy
image: ghcr.io/jens-maus/raspberrymatic-proxy
arch:
  - armv7
  - aarch64
  - amd64
description: Proxy to externally running RaspberryMatic CCU
url: https://github.com/jens-maus/RaspberryMatic
ingress: true
ingress_stream: true
panel_title: RaspberryMatic
panel_icon: mdi:router-wireless
boot: auto
init: true
timeout: 30
options:
  webui-url: http://homematic-raspi
schema:
  webui-url: str?
environment:
  HM_HAPROXY_SRC: 172.30.32.2/32
