name: Helm chart - build development version

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: 
      - completed

env:
  # NOTE: secrets cannot be access directly in conditions
  # https://github.com/actions/runner/issues/520
  SECRETS_ARE_AVAILABLE: ${{ secrets.GITHUB_TOKEN != '' }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get Version
      id: env
      run: |
        echo "VERSION=$(grep 'OCCU_VERSION =' buildroot-external/package/occu/occu.mk | cut -d' ' -f3 | cut -d'-' -f1).$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Publish testing Helm chart after sucesfull 
      if: env.SECRETS_ARE_AVAILABLE == 'true'
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        charts_dir: helm
        chart_version: 0.1
        app_version: ${{ env.VERSION }}