# RaspberryMatic pull-request checks

name: PR checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  linters:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check Dockerfile
      uses: reviewdog/action-hadolint@v1    

    - name: Check shell scripts
      uses: reviewdog/action-shellcheck@v1
