name: Set OCI tag
on:
  workflow_dispatch:
    inputs:
      source_tag:
        description: 'Source tag'
        required: true
        default: "snapshot"
      target_tag:
        description: 'Target tag'
        required: true
        default: "latest"

jobs:
  tag:
    name: Set OCI tag
    runs-on: ubuntu-20.04
    steps:
  
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    
    - name: build and push container image
      run: |
        BASE_TAG="ghcr.io/${{ github.repository_owner }}/raspberrymatic"
        SOURCE_TAG="${BASE_TAG}:${{ github.event.inputs.source_tag }}"
        TARGET_TAG="${BASE_TAG}:${{ github.event.inputs.target_tag }}"
        
        echo "Pulling ${SOURCE_TAG}"
        docker pull "${SOURCE_TAG}"
        docker tag "${SOURCE_TAG}" "${TARGET_TAG}"
        echo "Pushing ${TARGET_TAG}"
        docker push "${TARGET_TAG}"
